### PR TITLE
[TASK] Add indexing of content elements with sys_language_uid = -1

### LINKED ISSUE #197: Indexer can't handle pages with sys_language_uid = -1
Hey everyone,
first things first: Great work! Great extension!

Issue:
Pages with sys_language_uid = -1 will not be indexed. The problem exists in method checkIfpageShouldBeIndexed and addLocalizedPagesToCache in file Classes/indexer/types/class.tx_kesearch_indexer_types_page.php:

```php
public function checkIfpageShouldBeIndexed($uid, $language_uid) { // $uid = 123, $language_uid = -1
	$index = true;

	// ...

	if (!in_array($this->cachedPageRecords[$language_uid][$uid]['doktype'], $this->indexDokTypes)) {
		// $this->cachedPageRecords[-1][123]['doktype'] is NULL everytime, because it doesn't exist 
		$index = false; // everytime false, because in_array fails with cache $this->cachedPageRecords[-1]
	}
	return $index;
}
```
So pages with sys_language_uid = -1 will not be added in method addLocalizedPagesToCache, because foreach statement only handles existing sys languages:

```php
public function addLocalizedPagesToCache($pageRow) {
	// ...

	// create entry in cachedPageRecods for additional languages, skip default language 0
	foreach ($this->sysLanguages as $sysLang) { // doesn't work with sys_language_uid = -1
		if ($sysLang[1] > 0) { // doesn't work with sys_language_uid = -1
				list($pageOverlay) = \TYPO3\CMS\Backend\Utility\BackendUtility::getRecordsByField('pages_language_overlay', 'pid', $pageRow['uid'], 'AND sys_language_uid=' .intval($sysLang[1]));
			if ($pageOverlay) {
				$this->cachedPageRecords[$sysLang[1]][$pageRow['uid']] = \TYPO3\CMS\Core\Utility\GeneralUtility::array_merge($pageRow, $pageOverlay);
			}
		}
	}
}
```

Can you tell me if you plan to fix this mentioned issue in the future?

Best regards and thanks

### PR DESCRIPTION
**Pull request by sturm-solutions**
Resolves #197

### CODE REVIEW

**Comment by teaminmedias-pluswerk** [comment]
I made the former branch "compat9" the new "master" branch - therefore this pull request has been closed automatically.
Please create a new one if you feel it is still relevant.
Thank you!

**Comment by yesjoar** [comment]
@teaminmedias-pluswerk You don't find this relevant? Currently content elements with sys_language_uid = -1 aren't indexed. Is this the correct behaviour for you? Just asking.

I current ran into the same problem and don't know how to fix this.

**Comment by christianbltr** [comment]
No, I did not mean it is not relevant. The issue has been closed automatically. I will re-open it.

**Comment by christianbltr** [comment]
This has been fixed in https://github.com/teaminmedias-pluswerk/ke_search/commit/9152b0b21abf99f7fdb39ffa8e26a9582d96076f
and will be in next version after 3.0.4

**Pull request closed without merging**
