### PR TITLE
Fix userfunc and TCA definition 

### PR DESCRIPTION
**Pull request by kpurrmann**

### CODE REVIEW

**Comment by christianbltr** [comment]
Thanks, but I'd like to ask for a few changes to your commit:

Splitting up the TCA definitions is a good thing, but according to https://docs.typo3.org/typo3cms/TCAReference/WhatIsTca/Index.html the separate files should _return_ an array, not set one directly.

You changed the name in composer.json to kpurrmann/ke_search, this should be teaminmedias-pluswerk/ke_search.

_(changed comment, I see that the pull requests contains severel commits)_

**Comment by christianbltr** [comment]
Sorry, I noticed that you did several commits and changed my first comment accordingly.

**Comment by kpurrmann** [comment]
Sorry for that. Did not want to do that. You can close this PR and I will check this next week and will create several ones

**Comment by christianbltr** [comment]
Great, thanks!

**Pull request closed without merging**
