### PR TITLE
Fixes #124 - Translation of Filter Options does not work

### LINKED ISSUE #124: Translation of Filter Options does not work
We have TYPO3 7.6.18 and KE_search 2.4.3 in 7 Languages.
As we need sometimes Website Content only in one language that does not exist in default language, we need to set in typoscript 

config.sys_language_overlay = 0 
sys_language_mode = strict

Creating localized Filters Options for different languages works, but in Frontend only default language is show. 

Reason looks for me in 
ke_search/Classes/lib/class.tx_kesearch_filters.php

	`
	   public function languageOverlay(array $rows, $table) {

		if(is_array($rows) && count($rows))  {

			foreach($rows as $key => $row) {

				if(is_array($row) && $GLOBALS['TSFE']->sys_language_contentOL ) {

					$row = $GLOBALS['TSFE']->sys_page->getRecordOverlay(`

changing typoscriot to config.sys_language_overlay = 1 helps, but we need this setting 

So: this function it will never try to getRecordOverlay ... 
changing the code like the example below helps

	`
	   public function languageOverlay(array $rows, $table) {

		if(is_array($rows) && count($rows))  {

			foreach($rows as $key => $row) {

				if(is_array($row) && $GLOBALS['TSFE']->sys_language_content ) {

					$row = $GLOBALS['TSFE']->sys_page->getRecordOverlay(`

( Just check if we are in a translated Version of the Website or if sys_language_content hat fallback to default language instead of the used language mode by removing the "OL"  in if condition **$GLOBALS['TSFE']->sys_language_contentOL** )

I can fork this reposity and create a pull request. but as i saw you pushed 3 hours ago to a feature branch, shall i do my change on master or on your actual feature ?

### PR DESCRIPTION
**Pull request by velletti**
See Issue #124 

Just check if we are in a translated Version of the Website or if sys_language_content has fallback to default language instead of the used language mode by removing the "OL" in if condition $GLOBALS['TSFE']->sys_language_contentOL )

### CODE REVIEW

**Comment by velletti** [comment]
See Issue #125 

https://github.com/teaminmedias-pluswerk/ke_search/issues/125

This code Chnage is online since one week on our ke search instance ..

**Comment by velletti** [comment]
See Issue #127 

https://github.com/teaminmedias-pluswerk/ke_search/issues/127

**Comment by velletti** [comment]
See issue #128  

That was the last Pull request concerning the filters ..

**Comment by a-r-m-i-n** [comment]
Successfully tested. Works for me, in addition with https://github.com/teaminmedias-pluswerk/ke_search/pull/146

**Pull request merged**
