### PR TITLE
Feature/extbase backend module

### PR DESCRIPTION
**Pull request by bernhardberger**
I took the liberty and converted the Backend Module to an Extbase conform Backend Module. I didn't really touch the output configuration inside the single actions.

Tested in 6.2 LTS and 7.6 LTS.

Same functionality as before, no feature updates, just a simple refactoring job.

### CODE REVIEW

**Comment by christianbltr** [comment]
After merging the branch I get
Could not analyse class: "TeaminmediasPluswerk\KeSearch\Controller\BackendModuleController" maybe not loaded or no autoloader? 
when trying to access the backend module.

**Comment by bernhardberger** [comment]
Try to clean the install tool cache. If you're on 7.x also try erasing the
typo3temp/autoload folder
Am 11.04.2016 15:05 schrieb "Christian Bülter" notifications@github.com:

**Comment by christianbltr** [comment]
Sorry, still the same error.

That's what I did:
- clearing install tool cache
- rm -rf typo3temp/*
- manually clearing all cache tables

Test environment TYPO3 7.6.4

**Comment by bernhardberger** [comment]
Hmmm.. very strange. I'll check that when I'm back at the pc and get back
to you.
Am 11.04.2016 15:13 schrieb "Christian Bülter" notifications@github.com:

**Comment by bernhardberger** [comment]
At first glance it seems like an autoloader issue though.. are you running
TYPO3 in composer mode or default? If you have opcache enabled please also
try to clear the opcache..
Am 11.04.2016 15:14 schrieb "Bernhard Berger" bernhard.berger@gmail.com:

**Comment by christianbltr** [comment]
I tested it in composer mode.
Maybe adjustments are needed to the composer.json file?

**Comment by bernhardberger** [comment]
Most likely. U fortunately I don'd have a composer setup to test at hand.. usually this error occurs when either typo3temp/autoload doesn't get cleared sfter introducong composer.json or it simlly gets confused by the other teaminmedias-pluswerk psr entry..

**Comment by BenjaminBeck** [comment]
Hi @christianbltr
did you do a `composer dump-autoload` to generate the composer autoloader file?

**Comment by christianbltr** [comment]
Re-generating the autoload files with "composer dump-autoload" did the trick.

Merged to master, will be in next version after 2.2.1.

Thanks for this patch, it's an important step to make the whole extension based on extbase.

**Comment by bernhardberger** [comment]
Just for info: in 7.x the API for Backend Module Layouting has completely changed.

This still works just fine like in 6.2, but it won't be as pretty as BackendModules developed using the new API (missing progressbar at the top, buttonbar and function menu have slightly different spacing)

**Comment by mrvoss** [comment]
After updating to latest HEAD, I was bitten by the autoloader issue, too. I think requiring everyone updating ke_search to run "composer dump-autoload" is asking a little too much.

I noticed the new 'autoload' => array (...)' lines in ext_emconf.php. I think these 3 lines are the culprit (I think they overwrite the _2_ entries from composer.json), and removing them fixes the autoloader issue, w/o requiring to run "composer dump-autoload".

**Pull request merged**
