### PR TITLE
[TASK] add support to index shortcut elements for tt_content indexer

### PR DESCRIPTION
**Pull request by schugabe**
Until now the inserted records are not considered for indexing with the tt_content indexer.

This PR adds shortcut handling to the tt_content indexer.
Without the "shortcut" type in the "Content element types which should be indexed" option of the indexer the behavior is not changed (except that shortcuts are ignored in the processing loop).

If "shortcut" is added to the CType config of the indexer the inserted elements are added to the list of items (only other tt_content items are supported. All other formats like news,... are ignored).

### CODE REVIEW

**Comment by teaminmedias-pluswerk** [comment]
Thank you for that patch.

I think it would be great if that feature would also be available in the pages indexer and since the tt_content indexer inherits from the pages indexer it would make sense to implement it in the pages indexer in the first place.

Also please keep in mind that we're working heavily on version 3 which will be compatible with TYPO3 v9 only so maybe it would make sense to implement it in the branch compat9 (https://github.com/teaminmedias-pluswerk/ke_search/tree/compat9) or wait with a new merge request until compat9 is merged into master.

It looks like this patch than would fix https://github.com/teaminmedias-pluswerk/ke_search/issues/234 also.

**Comment by schugabe** [comment]
I added it to the tt_content indexer because a customer uses the tt_content indexer and noticed that shortcuts are missing. Tbh I did not check what the pages indexer does in this case... Without looking into it I assumed that the pages indexer fetches the rendered pages and the tt_content indexer works on the content elements. But now I looked in the code of the page indexer and don't really understand why there are two variants of the tt_content indexing.

**Comment by teaminmedias-pluswerk** [comment]
The page indexer puts the content of a whole page into one index record. The advantage here is, that you do not have multiple results for the same page. That is supposed to be the best practice approach.

The tt_content indexer creates on index record for each content element. The advantage here is, that you can jump to the content element by clicking on the search result. But you will have several results for the same page if the search word appears in multiple content elements in one page.

**Comment by teaminmedias-pluswerk** [comment]
I made the former branch "compat9" the new "master" branch - therefore this pull request has been closed automatically.
Please create a new one if you feel it is still relevant.
Thank you!

**Pull request closed without merging**
