### PR TITLE
[FEATURE] In pagebrowser, split up the link data

### PR DESCRIPTION
**Pull request by rowild**
Currently, the styling of the pagebrowser links as well as adding more attributes to them (like aria, rel, custom text from languge.xlf, nested tags [for e.g. FontAwesome], etc) is cumbersome. Splitting up the available data for page links into a multidimensional array like this:

```
$links['pages'][$i]['url'] = $this->cObj->typoLink_URL($linkconf);
$links['pages'][$i]['pageNumber'] = $i;
$links['pages'][$i]['link'] = $this->cObj->typoLink($i, $linkconf);
```
allows for a more flexible styling and adding of attributes in fluid. 

Fluid example:

```
[...] 
<!-- Pagination -->
<f:if condition="{pagebrowser.pages_total} > 0">

    <!-- Previous page -->
    <f:if condition="{pagebrowser.links.previous.url} != ''">
        <f:then>
            <a href="{pagebrowser.links.previous.url}" rel="prev" class="prev">
                <span class="u-hidden-visually">
                    <f:translate key="pagination.prev" extensionName="theme"/>
                </span>
                <i class="fa fa-chevron-left" role="presentation"></i>
            </a>
        </f:then>
        <f:else>
            <span class="u-hidden-visually">
                <f:translate key="pagination.prev" extensionName="theme"/>
            </span>
            <i class="fa fa-chevron-left inactive" role="presentation"></i>
        </f:else>
    </f:if>

    <!-- Page Numbers -->
    <f:for each="{pagebrowser.links.pages}" as="page">
        <f:if condition="{page.current}">
            <f:then>
                <i class="fa current" role="presentation">{page.pageNumber}</i>
            </f:then>
            <f:else>
                <a href="{page.url}">
                    <i class="fa" role="presentation">{page.pageNumber}</i>
                </a>
            </f:else>
        </f:if>
    </f:for>

    <!-- Next Page -->
    <f:if condition="{pagebrowser.links.next.url} != ''">
        <f:then>
            <a href="{pagebrowser.links.next.url}" rel="next" class="next">
                <span class="u-hidden-visually">
                    <f:translate key="pagination.next"/>
                </span>
                <i class="fa fa-chevron-right" role="presentation"></i>
            </a>
        </f:then>
        <f:else>
            <span class="u-hidden-visually">
                <f:translate key="pagination.next"/>
            </span>
            <i class="fa fa-chevron-right inactive" role="presentation"></i>
        </f:else>
    </f:if>
</f:if>
[...]
```

### CODE REVIEW

**Comment by christianbltr** [comment]
I would prefer to have a fluid rendered pagebrowser instead of introducing a breaking change in the "old" style pagebrowser.
See also https://github.com/teaminmedias-pluswerk/ke_search/issues/22

**Comment by rowild** [comment]
I second that idea!!!

**Comment by drmmch** [comment]
I made a PR for that, see #183 
Can you estimate when you're going to review the PR?

**Comment by christianbltr** [comment]
Sorry, I'm very busy with projects at the moment. I try to find time as soon as possible.

**Comment by christianbltr** [comment]
resolved with https://github.com/teaminmedias-pluswerk/ke_search/pull/183

**Pull request closed without merging**
