### PR TITLE
use 0 as default value for id-columns

### PR DESCRIPTION
**Pull request by infabo**

### CODE REVIEW

**Comment by christianbltr** [comment]
Thank you. 

This patch fixes https://github.com/teaminmedias-pluswerk/ke_search/issues/190, right?

I think the strrev part (and maybe the patch altogether) may not understandable by reading if you look at the code in some time ahead. Could you therefore add a comment which explains this, please?

**Comment by infabo** [comment]
Yes, this is a quick-fix for #190. A mapping of known integer-columns would be fail-safe. But a column-name ending with "id" is in 99,9% of cases -> INT. So i guess using `0` is pretty safe here. I will comment it or use another more-readable check for "string-ends-with". brb

**Comment by infabo** [comment]
OK, found out that TYPO3 Core already provides an endsWith comparison with StringUtility.

**Comment by christianbltr** [comment]
I'm not sure: Wouldn't it be better to use specifically "orig_uid" and "orig_pid"? It is only a guess, that all fields ending with "id" are of type integer. Also we have "sortdate" as an additional field already in ke_search which does not end with "id".

So I think it would be better to set the default value "0" for the fields "orig_uid", "orig_pid" and "sortdate". If third-party extensions add more additional fields, they would have to take care about setting the right default value.

**Comment by infabo** [comment]
As of 2.8.0 orig_uid changed to varchar. So whats left is: `orig_pid` (where I had my issue with MySQL 5.7) and `sortdate`.

**Pull request closed without merging**
